//
//  main.swift
//  Calculate Even Fibonacci
//
//  Created by Pierre Oosthuizen on 2020/01/10.
//  Copyright © 2020 Plouton Consulting. All rights reserved.
//

import Foundation

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

func main() {
    
    var value1: Int = 1
    var value2: Int = 2
    var fibSum: Int = 2

    while (value2 < 4000000) {
        let valueSum = value1 + value2
        
        if (valueSum % 2) == 0 {
            fibSum += valueSum
        
        value1 = value2
        value2 = valueSum
    }

    print ("Total: ", fibSum)
}
